### PR TITLE
Fixes problems with spaces in the original URL

### PR DESCRIPTION
**Pull request by leolabs**

### CODE REVIEW

**Comment by harto** [comment]
Hi, could you please describe the problem you're trying to solve?

**Comment by leolabs** [comment]
When the url of the original image contains white spaces, the generated key will not be valid as most browsers will convert them to %20 afterwards. This is why I decided to let phumbor convert the original url before signing it.

**Comment by kkopachev** [comment]
I think it should not replace `/`, so that would work better: 
```php
$this->original = implode('/', array_map('rawurlencode', explode('/', $original)));
```

**Comment by beltofte** [comment]
Any plans to merge this pull request? I can confirm that the solution from @kkopachev works as expected when the original URL contains white spaces.

**Comment by harto** [comment]
I'm not involved any more, perhaps @arthens could take a look ;)

**Comment by Sonna** [comment]
@arthens (Last active 99designs dev involved with this Pull Request)

Can we close this Pull Request (PR) for the following reasons?

- Inactive for over 3 years
- This project's last commit was `23 Jan 2017`, so is likely stable, inactive, unused or all the above
- ~_"I believe Thumbor was replaced by [Tapestry](https://github.com/99designs/tapestry)?"_~
  > tapestry _is_ thumbor
- @leolabs, @harto, @kkopachev & @beltofte do not appear to be members of the 99designs organisation on GitHub (at the time of writing) and cannot easily further contribute to this PR
  + https://github.com/orgs/99designs/people?utf8=✓&query=leolabs
  + https://github.com/orgs/99designs/people?utf8=✓&query=harto
  + https://github.com/orgs/99designs/people?utf8=✓&query=kkopachev
  + https://github.com/orgs/99designs/people?utf8=✓&query=beltofte
- Failing build check
  + Also uses Travis CI over Buildkite (old build/deploy environment)
- Pull Request can be easily re-opened if need be

**Comment by arthens** [comment]
yes close it, we'll re-open it if appropriate

**Pull request closed without merging**
